export const INVENTORY_STATUS = {
    UNCLAIMED: 'UNCLAIMED',
    PENDING_DROPOFF: 'PENDING_DROPOFF',
    PENDING_STORE_PICKUP: 'PENDING_STORE_PICKUP',
    PENDING_COURSE_PICKUP: 'PENDING_COURSE_PICKUP',
    PICKUP_OVERDUE: 'PICKUP_OVERDUE',
    FOR_SALE: 'FOR_SALE',
    CLAIMED: 'CLAIMED',
    SOLD: 'SOLD',
    SOLD_OFFLINE: 'SOLD_OFFLINE',
    SURRENDERED: 'SURRENDERED'
}

export const DISC_CONDITION = {
    EXCELLENT: 'Excellent',
    GREAT: 'Great',
    GOOD: 'Good',
    FAIR: 'Fair',
    POOR: 'Poor'
}

export const PICKUP_PREFERENCE = {
    WEEKDAY_MORNING: 'Weekday Morning',
    WEEKDAY_AFTERNOON: 'Weekday Afternoon',
    WEEKDAY_EVENING: 'Weekday Evening',

    WEEKEND_MORNING: 'Weekend Morning',
    WEEKEND_AFTERNOON: 'Weekend Afternoon',
    WEEKEND_EVENING: 'Weekend Evening',
}
